### ISSUE TITLE
How to get the masks in the first frame?

### ISSUE THREAD

**Issue by YJessicaGao** [lxx1991/VS-ReID#12]
Hi, there.

How can I get the 'Guided Probability Map' mentioned in your paper, if I use my own video sequence.

**Comment by danielkaifeng** [comment]
you can use image segmentation model like MaskRCNN to get the first frame

**Comment by YJessicaGao** [comment]
got it, thanks!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "daniel_deng"<notifications@github.com&gt;; 
发送时间: 2019年12月4日(星期三) 下午5:19
收件人: "lxx1991/VS-ReID"<VS-ReID@noreply.github.com&gt;; 
抄送: "高雨佳"<937073104@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [lxx1991/VS-ReID] How to get the masks in the first frame? (#12)




you can use image segmentation model like MaskRCNN to get the first frame
