### ISSUE TITLE
Array Size Mismatch error

### ISSUE THREAD

**Issue by bach-zouk** [lxx1991/VS-ReID#2]
This is after running the code on DAVIS test set.

  result = prob_to_label(combine_prob(pred_prob[th]))
  File "/media/abhishek/Data1/src_codes/VS-ReID/core/utils/bbox.py", line 46, in combine_prob
    temp_prob[..., i] = prob[..., i * 2 - 1]
ValueError: could not broadcast input array from shape (480,854,3) into shape (480,854)

**Comment by lxx1991** [comment]
Hi,
Did you remove the color-map from the original annotations? 

Since opencv could not directly read the index from the png file with color-map, you may need to use following Matlab statements to remove the color-map.

```Matlab
ann, cmap = imread('annfile.png')
imwrite(ann, 'new_annfile.png')
```

**Comment by bach-zouk** [comment]
No, I did not..Thank you very much for swift reply. I will confirm and close it in few hours.

**Comment by pankajvshrma** [comment]
I am also getting the same error. Where you able to resolve it @Not-IITian

**Comment by bach-zouk** [comment]
Just write a small script to remove color-map as lxx1991 suggested.. i can attach one here in an hour

**Comment by Agent-Chu** [comment]
> Just write a small script to remove color-map as lxx1991 suggested.. i can attach one here in an hour

Hi, can you attach the remove script? Thank you very much!
