### ISSUE TITLE
Does everyone have the flow data for DAVIS2017 in the paper? I am puzzled with the dataset

### ISSUE THREAD

**Issue by ranranxu95** [lxx1991/VS-ReID#7]

**Comment by lxx1991** [comment]
Hi, there is no flow data in the zip file, since file size is too large.

As mentioned in the readme, you can use the [FlowNet2.0](http://github.com/lmb-freiburg/flownet2) to extract the optical flow for the whole dataset.

**Comment by ranranxu95** [comment]
Thank you very much. I will do it by myself.
